---
title: "Demographic identity and the choice of cooking fuel: evidence from post-earthquake Nepal"

author:
  - name: "**Ratna K. Shrestha**"
    affiliation: Vancouver School of Economics, University of British Columbia
  - name: "**Raunak Shrestha**"
    affiliation: Department of Radiation Oncology, University of California San Francisco

output: html_document

knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

### Abstract
> Over 72% of people in Nepal do not have access to clean cooking fuels; this aggregate statistic masks significant heterogeneity in access across different demographic subgroups. In this paper, using data collected in the aftermath of Nepal’s 2015 earthquake, we construct a link between households’ choice of fuel types and their demographic identities. We then employ PERMANOVA and find that ethnicity explains the highest intergroup heterogeneity (39.1%) in cooking fuel choice, followed by income (26.3%), education (12.6%), and geo-climatic location (4.1%). An interaction between any two demographic factors contributes less than 3.5% of total variation. Among the ethnic groups, Chepang/Thami exhibit the lowest intragroup diversity (Shannon Index 0.101) while Newar the highest (0.667). These results underscore the importance of policies based on ethnicity, rather than other demographic factors, in promoting an equal and just access to clean cooking and identifying the population subgroups that are vulnerable to fuel supply disruptions.

### Dataset
Following the 7.8 Mw Gorkha Earthquake in Nepal on April 25, 2015, the Kathmandu Living Labs in collaboration with the National Planning Commission (the Government of Nepal), carried out the largest household survey ever done in Nepal using mobile technology. Although the primary objective of this survey was to assess damages inflicted by the quake and identify beneficiaries eligible for government’s housing reconstruction grants, the data contain many other kinds of valuable socio-economic information, including the types of fuel used by households for cooking and lighting from 11 of the most earthquake-affected districts of Nepal, excluding the Kathmandu valley. 

The data for all 11 districts were downloaded from the **2015 Nepal Earthquake: Open Data Portal** (<http://eq2015.npc.gov.np/>). 
<br/><br/>

#### Code availability
R-codes used for data analysis is available at [https://github.com/shrestha-ratna/cooking-fuel-diversity](https://github.com/shrestha-ratna/cooking-fuel-diversity)
<br/><br/>

#### Citation
Shrestha, Ratna K. and Shrestha, Raunak. **Demographic identity and the choice of cooking fuel: evidence from post-earthquake Nepal**. 2021. (*submitted*) earlier version: [https://arxiv.org/abs/2005.09616](https://arxiv.org/abs/2005.09616) <br/>
<br/><br/>

#### Corresponding author
Ratna K. Shrestha, PhD <br/>
Vancouver School of Economics, <br/>
University of British Columbia, <br/>
6000 Iona Drive, Vancouver, BC, Canada V6T 1L4 <br/>
E-mail: ratna [dot] shrestha [at] ubc.ca<br/>

